# Generated by Django 4.2 on 2024-10-31 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0002_remove_inscrit_id_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscrit',
            name='domaine_etude',
            field=models.TextField(default='', max_length=40),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='niveau_etude',
            field=models.TextField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='inscrit',
            name='phone',
            field=models.TextField(default='', max_length=10),
        ),
    ]
