# Generated by Django 4.2 on 2024-10-31 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0003_inscrit_domaine_etude_inscrit_niveau_etude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inscrit',
            name='phone',
        ),
        migrations.AddField(
            model_name='inscrit',
            name='phone_number',
            field=models.TextField(default='', max_length=20),
        ),
    ]
