# Generated by Django 4.2 on 2024-11-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0011_alter_inscrit_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscrit',
            name='niveau_etude',
            field=models.TextField(default='', max_length=100),
        ),
    ]
