# Generated by Django 4.2 on 2024-11-06 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0012_alter_inscrit_niveau_etude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='ModuleFormation',
        ),
        migrations.DeleteModel(
            name='ModuleFormation',
        ),
    ]
