# Generated by Django 4.2 on 2024-11-06 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0009_remove_webinar_user_webinarenrollment_user'),
        ('programmeTalent', '0013_remove_seance_moduleformation_delete_moduleformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleFormation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formation', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation')),
                ('module', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.module')),
            ],
        ),
    ]
