# Generated by Django 4.2 on 2024-11-06 11:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0014_moduleformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='ModuleFormation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.moduleformation'),
        ),
    ]
