# Generated by Django 4.2 on 2024-11-06 15:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0009_remove_webinar_user_webinarenrollment_user'),
        ('programmeTalent', '0015_seance_moduleformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='ModuleFormation',
        ),
        migrations.AddField(
            model_name='seance',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation'),
        ),
        migrations.AddField(
            model_name='seance',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
    ]
