# Generated by Django 4.2 on 2024-11-06 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0017_seance_moduleformation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='formation',
        ),
        migrations.RemoveField(
            model_name='seance',
            name='module',
        ),
    ]
