# Generated by Django 4.2 on 2024-11-06 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0009_remove_webinar_user_webinarenrollment_user'),
        ('programmeTalent', '0018_remove_seance_formation_remove_seance_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='module',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
    ]
