# Generated by Django 4.2 on 2024-11-07 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0020_community_message_membership'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='community',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='community',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='Community',
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
