# Generated by Django 4.2 on 2024-11-07 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0021_remove_membership_community_remove_membership_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('lieu', models.CharField(max_length=255)),
                ('date_cours', models.DateField()),
                ('description', models.TextField()),
                ('date_publication', models.DateField(auto_now_add=True)),
                ('heure', models.TimeField()),
            ],
        ),
    ]
