# Generated by Django 4.2 on 2024-11-11 16:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0022_annonce'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonce',
            name='date_publication',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='annonce',
            name='heure',
            field=models.TimeField(default=datetime.date.today),
        ),
    ]
