# Generated by Django 4.2 on 2024-11-13 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Formation', '0009_remove_webinar_user_webinarenrollment_user'),
        ('programmeTalent', '0024_alter_annonce_heure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleformation',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation'),
        ),
        migrations.AlterField(
            model_name='moduleformation',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Formation.module'),
        ),
    ]
