# Generated by Django 4.2 on 2024-11-14 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0025_alter_moduleformation_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='formation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='programmeTalent.formation'),
        ),
    ]
