# Generated by Django 4.2 on 2024-11-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0027_seance_heure_fin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='ModuleFormation',
        ),
    ]
