# Generated by Django 4.2 on 2024-11-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0028_remove_seance_moduleformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
