# Generated by Django 4.2 on 2024-11-14 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0030_alter_seance_statut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='statut',
            field=models.CharField(choices=[('confirmé', 'confirmé'), ('annulé', 'annulé'), ('attente', 'attente')], default='attente', max_length=10),
        ),
    ]
