# Generated by Django 4.2 on 2024-11-15 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0031_alter_seance_statut'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='location',
        ),
        migrations.AddField(
            model_name='formation',
            name='localition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
