# Generated by Django 4.2 on 2024-11-15 18:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0032_remove_formation_location_formation_localition'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='date',
            field=models.DateField(default=datetime.date(2024, 1, 20)),
        ),
    ]
