# Generated by Django 4.2 on 2024-11-15 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programmeTalent', '0033_formation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='localition',
        ),
        migrations.AddField(
            model_name='formation',
            name='localisation',
            field=models.CharField(default='FIDALLI', max_length=200),
        ),
    ]
